### ISSUE TITLE
Improve/replace dateformat

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/n-express#18]
- doesn't need to be a block helper
- should use o-date

Maybe deprecate existing one and add new one e.g `{{oDate date format="YYYY"}}`

I'll do a PR next week if this sounds good @matthew-andrews

**Comment by matthew-andrews** [comment]
what would the output be?

**Comment by matthew-andrews** [comment]
This is a good idea, thanks @wheresrhys. I think it's worth keeping it outputting text as it does now but maybe an option `wrapInTimeTag`* that outputs it in a totally Origami type way.

As for deprecating the old one suggest adding some code like this:-

```js
errorHandler = require('express-errors-handler');

if (process.env.NODE_ENV === 'production') {
  errorHandler.captureMessage("Using old date helper");
} else {
  throw new Error("Using old date helper");
}
```

\* please improve this name

**Comment by wheresrhys** [comment]
{{oDate date }} -> standard FT format
{{oDate format='iso' }} -> iso
{{oDate format='YYYYMMMMDDDD'}} -> formatted as expected

Maybe worth still delegating to node/dateformat for anything but the standard format

**Comment by wheresrhys** [comment]
yep good idea

**Comment by matthew-andrews** [comment]
^^ nice!  perfect.
