### ISSUE TITLE
Implementation of flags on <html> element is not safe

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/n-express#190]
In all other cases when we delete flags the feature reverts to being off, but for this case the opposite is true.

This is only used by one single feature (image service icons) — which I think was to work around a bug we were regularly running into with font icons……  Since then I think we have decided font icons are a bad idea™ and for the benefits of safety and simplicity I propose just removing this feature…

https://github.com/search?q=data-next-flags&type=Code&utf8=%E2%9C%93

cc @wheresrhys.

**Comment by wheresrhys** [comment]
Good point. It's not there for that reason. It was added for when image service went down (or possibly just the tinting endpoint) and we had no icons which resulted in things looking broken. I'm not sure if that's something we need to worry much about now. Although it'd be nice to have a safe way to pass a feature flag's state in to styles that wouldn't require a template change fro each flag... useful for AB testing site-wide style changes. Maybe flags could have a `css: true` attribute, in which case if the flag is on it is added to the `data-next-flags` attribute

**Comment by matthew-andrews** [comment]
In that case I think in the future it would be completely fine to spit out all the on flags into the `<html>` element. ie.  `data-next-flags="ads alphasurvey analytics articleCapiV1Fallback articleComments…"`… etc etc.  We already dump all the flags data into the page body anyway…… and in fact we could even probably rely solely on the `data-next-flags` attribute — ie the javascript client could just use that.

**Comment by wheresrhys** [comment]
My concern with that is that then you have a huge - and growing - data
attribute. Could be performance concerns about using this as a selector in
older, and maybe even modern browsers. I don't know enough about
tokenisation of attributes, so possibly this concern is unwarranted.

On 5 July 2015 at 10:41, Matt Andrews <notifications@github.com> wrote:

> In that case I think in the future it would be completely fine to spit out
> all the on flags into the <html> element. ie. data-next-flags="ads
> alphasurvey analytics articleCapiV1Fallback articleComments…"… etc etc.
> We already dump all the flags data into the page body anyway…… and in fact
> we could even probably rely solely on the data-next-flags attribute — ie
> the javascript client could just use that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/next-express/issues/190#issuecomment-118602392>
> .
>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.
