### ISSUE TITLE
Force hashed assets to be declared more explictly

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/n-express#299]
In order to reduce the risk that we ship code without hashed assets @ironsidevsquincy and I propose requiring developers to declare the **built path** for built JS/SCSS assets that they're using in the either the `bower.json` or the `package.json` file in a repo.

```
{
…
  "hashedAssets": [
    "public/main.js",
    "public/main.css"
  ]
…
}
```

A major new version of `next-express` will refuse to start unless those files exist **and** the `asset-hashes.json` file exists **and** contains mappings from those paths to their equivalent hashed paths.  I **don't** think we should also poll the internet to check that 

`nbt build` (and/or its n-makefile equivalent) will change to rather than [accept arguments](https://github.com/Financial-Times/next-es-interface/blob/master/Makefile#L25-L28) to iteration through that list and build all the required assets (although we'll probably keep options to override this for _edge cases_) and double check that they exists (and fail the build if something goes awry).  This will also have a nice extra benefit of speeding up some builds as the building of the assets can run in parallel.

cc @wheresrhys @ironsidevsquincy 

**Todo:-**
- [ ] Decide whether to put this in `bower.json` or `package.json`.
- [ ] Write more items in the todo list.

**Comment by wheresrhys** [comment]
Would this protect against e.g. an app accidentally gets `main.css` deleted from this list? Unless I'm missing something that'd surely leave us vulnerable to main.css not getting deployed. Should it run an inverse check too - any files that exist in public without an entry in hashed assets will cause an error too?

Is next-express the right place for this? Why not nbt/n-makefile?

I'd favour putting it inside a `ft: {hashedAssets}` property on package.json

**Comment by matthew-andrews** [comment]
just put in this in next-express as somewhere to dump the issue, also planning to put stuff in makefile and nbt.
+1 to doing an inverse check
+1 to having it namespaced as well

**Comment by matthew-andrews** [comment]
How about:-

**package.json:-**
```js
{
…
  "n-makefile": {
    "entry": {
      "client/main.scss": "public/main.css",
      "client/main.js": "public/main.js"
    }
  }
…
}
```

**Comment by ironsidevsquincy** [comment]
That's a good idea. feels like we're creating an `n-makefile` config now, so any reason to keep it in package.json? could just have a `n-makefile.json`

**Comment by matthew-andrews** [comment]
oooh `n-makefile.json` hmm………

**Comment by wheresrhys** [comment]
If we go down that path I'd prefer yaml. In fact why not go for next.yml as a multipurpose container for nexty stuff. Or another contender would be to overload circle.yml

Don't really mind, other than preferring yaml

**Comment by matthew-andrews** [comment]
does webpack already have such a concept?

**Comment by matthew-andrews** [comment]
prefer to use something with native integration with node…  so maybe no to yml unless i'm mistake…?

**Comment by wheresrhys** [comment]
Doesn't your example code above still leave us vulnerable to an accidentally deleted line meaning an asset doesn't get built and doesn't get checked for? For this to be of any use in CI shouldn't declaration of what to build and what to expect be separated?

**Comment by matthew-andrews** [comment]
I think it's ok because if you removed a line you would break it locally too.

**Comment by matthew-andrews** [comment]
done
