### ISSUE TITLE
v16

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/n-express#301]
- [x] Force hashedAssets to be declared in a `n-makefile.json` file otherwise don't serve them, refuse to start if file doesn't exist.
- [x] Remove `/__sensu` integration
- [x] Rename to `@financial-times/n-express`
- [x] `n-makefile`-ify

**Comment by wheresrhys** [comment]
Could we also look at which flags (withBackendAuth, withHandlebars etc) are on by default. I think Just backendAuth needs to be on by default, but now that n-express mostly powers apis probably everything else should be off by default

also see https://github.com/Financial-Times/n-express/issues/305

**Comment by wheresrhys** [comment]
Also
- general audit of what should live in the src directory (bit arbitrary 
- remove `.nextLogger`

Controversial this, but consider making raven a global? Ease of use would mean it's more likely to be applied appropriately

**Comment by wheresrhys** [comment]
Also error handling - we could probably build something a bit better than the existing
