### ISSUE TITLE
Fork expressjs?

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/n-express#319]
Reasons
- our instrumentation interacts a lot with undocumented express internals, which is a dangerous practice
- wrapping these internals, in some cases several times is difficult, restrictive, and probably a slight performance hit
- the last change to express's source (excluding docs and dependency updates) was last august https://github.com/expressjs/express/commits/master?page=2, so I doubt we'd have much work to do merging in security patches and the like.

**Comment by bjfletcher** [comment]
If Express is dead, why keeping working off it? Is it time to look at Hapi et al? :)

**Comment by matthew-andrews** [comment]
👎 Forking express, 👍 to looking at alternatives.

Hapi is used at the FT already but would be good to look at the options and pick something that looks interesting+on the rise :-].

**Comment by wheresrhys** [comment]
koa2? Built on await/async. Still in beta though
