### ISSUE TITLE
Is it possible to configure a default layout in an n-express app?

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/n-express#336]
Should it be possible to configure a default layout in an n-express app?

Given that n-express uses n-handlebars,
https://github.com/Financial-Times/n-express/blob/master/package.json#L9

Should n-express call `nextifyHandlebars()` in n-handlebars?
https://github.com/Financial-Times/n-handlebars/blob/master/express.js#L25

**Comment by adambraimbridge** [comment]
Also, it's configured to default to `bower_components/n-layout/templates/`. 

https://github.com/Financial-Times/n-express/blob/master/main.js#L165

It's assuming you're using the n-layout bower component, but it doesn't bundle n-layout. Can we pick one or the other?

**Comment by wheresrhys** [comment]
It needs updating to point at n-ui/layout. But probably can't be bundled in... although I will try when I update it as - for layout rather than partials, it may not be 100% necessary to have the flat directory structure that bower guarantees

**Comment by wheresrhys** [comment]
covered by move to n-ui
