### ISSUE TITLE
Add the app name to the user agent string in isomorphic fetch

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/n-express#344]
Let's say an app built with n-express happens to be a little overzealous when fetching from some other API. Let's say we're asked by the API dev team to dial it down a bit. But they don't know which of our many apps is the culprit. 

If the user agent string in their logs had the name of our app, then we'd be at least one step closer to making everybody happy.

**Comment by wheresrhys** [comment]
nice idea. Off the top of my head I can't think of anything to be careful of
