### ISSUE TITLE
Remove navigation model

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/n-express#357]
This is [bundled with the anon middleware](https://github.com/Financial-Times/n-express/blob/98b434db1e4328e601608a301033d9fb9abbf803/src/anon/middleware.js#L20).

~~It is now only used [here](https://github.com/Financial-Times/next-product-selector/blob/a86a0c2d5616a6f9d6cdea8c64e13669b924cf6e/server/controllers/barriers.js#L58) and [here](https://github.com/Financial-Times/next-myft-page/blob/645e32f5ff3dd2736fe570c8f8e191e52ba8bb26/server/controllers/product-tour.js#L41).~~

The login and logout links are provided by the [n-navigation middleware](https://github.com/Financial-Times/n-navigation) and it is confusing having both.

**Comment by matthew-andrews** [comment]
nice clean up task
