### ISSUE TITLE
The error rate health check doesn't work

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/n-express#563]
https://github.com/Financial-Times/n-express/blob/ef9a0dd4813c4898be33001df0b894298024aca9/src/lib/error-rate-check.js#L14-L24

From Bren during the recent stream page incident:

> looks like the `n-express` error response threshold healthcheck isn’t working
> because stream page is currently >60% `500` responses

We have seen success in more simple uses in next-health, https://github.com/Financial-Times/next-health/blob/master/server/config/health-checks/service-unavailability.js.

**Comment by quarterto** [comment]
looks like, for `stream-page` at least, the graphite query uses the app name `next-stream-page`, but it's `stream-page` in the data.

this may be a problem with [`guessAppDetails`](https://github.com/Financial-Times/n-express/blob/master/src/lib/guess-app-details.js) (for `stream-page` or generally), but calling that function directly returns the right name.

this relates to Financial-Times/next#385

**Comment by quarterto** [comment]
ah, it's using the `systemCode` not the name (as provided by the app itself). changing the `systemCode` to `stream-page` would fix this check for that app, but since the actual Biz Ops system code is `next-stream-page` i don't think this is the correct fix. i'm looking into how `next-metrics` puts things into Graphite and why it's a different name

**Comment by quarterto** [comment]
jotting down ideas for future-Bren's benefit:

- we could do a combination `ebi` search/graphite call to check that there are no apps with a `systemCode` that doesn't exist in graphite
- it could become an `n-express` healthcheck! which checks graphite for an app with that system code.have to be careful because if we add it carelessly we'll suddenly get dozens of failing checks
- what else in `n-express` uses `systemCode`?

**Comment by quarterto** [comment]
this is the complete list of services with a broken `errorThreshold` healthcheck

```
ads-api
ammit-api
ammit-docs
api
article
b2b-prospect
barrier-guru
consent-proxy
control-centre
corp-signup
epaper
es-interface
eventpromo-api
feedback-api
flag-toggler
flags-api
fow-api
front-page
graphics-page
health
houston
kat-api
list-doctor
live-event-api
lure-api
media-api
messaging-guru
myft-api
myft-page
myft-proxy
myft-slow-jobs
navigation-api
next-magnet-api
next-subscribe
personalised-feed-api
popular-api
preflight
preview
product
profile
retention
router
search-api
search-page
session
signup
signup-api
signup-proxy
spoor-consumer
spoor-device-atlas-api
spoor-voltdb-health-api
static
stream-page
subscribe
syn-list
syndication-api
syndication-dl
tag-facets-api
tour-page
vault-editor
vault-sync
video-editor
video-page
webhooks
```

**Comment by sjparkinson** [comment]
> it could become an n-express healthcheck! which checks graphite for an app with that system code.have to be careful because if we add it carelessly we'll suddenly get dozens of failing checks

If we go down a route like this to get the system codes and graphite prefixes lined up, I'd prefer to raise an issue on the repo for this sort of thing. As a health check, it's only ever going to alert the once really.

**Comment by wheresrhys** [comment]
FYI system codes can change in biz ops. It's deliberately not obvious how to do it because if there are resources tagged in aws it has repercussions. But you could probably rename system code to match ft.com app names if you wanted to (though perhaps system code is a better choice in many cases)

**Comment by quarterto** [comment]
i think the route i'm going to take, if it's possible, is getting the expected system code _from_ graphite by UUID

**Comment by quarterto** [comment]
so, apparently that's not possible. solutions we've thought of, and why they're bad:

### rename the services in graphite to their actual system codes

this would break all our Grafana dashboards, _and_ break any custom healthchecks with a hardcoded system code (of which there are [a lot](https://github.com/search?p=2&q=org%3Afinancial-times+%22next.heroku%22&type=Code))

### look up prefix by UUID

this API doesn't exist

### add a separate options field to `n-express`, something like `graphiteSystemCode`

would require adding that field to all 62 broken services. this is probably the least bad option

### maintain a mapping of UUIDs to service names

this would be another source of truth. the list of services doesn't change that often but i'm wary

### parse the system code into something that looks like the graphite system code

they're not consistently named in graphite so this wouldn't fix every case

**Comment by quarterto** [comment]
i'm going for the "add a separate options field to `n-express`, something like `graphiteSystemCode`" option and doing a nori transform

**Comment by sjparkinson** [comment]
@quarterto this is resolved with everything being merged right?

**Comment by quarterto** [comment]
oh yeah! thanks
