### ISSUE TITLE
Append app metadata to app.locals

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/n-express#566]
This package is able to ["guess" and format several app details](https://github.com/Financial-Times/n-express/blob/master/src/lib/guess-app-details.js) including `name`, `systemCode`, and `graphiteName`.

These values are useful to our applications for debugging purposes and configuring name-dependent features such as hosting static assets.

However, these values are not currently accessible by applications using this package but Express has a few ways to help make them so; [settings](https://expressjs.com/en/api.html#app.set) or [app locals](https://expressjs.com/en/api.html#app.locals).

I propose that we add these app details as `app.locals.nExpressAppDetails` (or similar) so that applications can more easily reuse this information.

**Comment by rowanmanning** [comment]
I think we're not gonna do this, it's been a few years and now we have the [app-info](https://github.com/Financial-Times/dotcom-reliability-kit/tree/main/packages/app-info#readme) Reliability Kit package. This is already used under the hood by n-express and apps that need this data can install and import the dependency themselves.

@apaleslimghost and I would like to slowly reduce the amount of work that n-express is doing and reduce the coupling between it and our apps.
