### ISSUE TITLE
Export express types

### ISSUE THREAD

**Issue by gyss** [Financial-Times/n-express#637]
Hello Platforms team!

We are migrating `next-discovery-pages` to Typescript and we found a small issue when trying to type the Request/Response objects. Basically we are required to install / import them from `@types/express` and do some `@ts-ignore` to fix the fact that, for example the response object have extra properties:

https://github.com/Financial-Times/next-discovery-pages/pull/455/files

```
	const headers = {
		// @ts-ignore FT_NO_CACHE not available in res
		'Cache-Control': page.cacheControl || res.FT_NO_CACHE,
		// @ts-ignore FT_DAY_CACHE not available in res
		'Surrogate-Control': page.surrogateControl || res.FT_DAY_CACHE,
		'Surrogate-Key': surrogateKeys.join(' '),
	}
```

We were wondering if it would be possible that `n-express` exports the extended express types so the migration is more straightforward.

**Comment by apaleslimghost** [comment]
hi @gyss! i've raised [a ticket](https://financialtimes.atlassian.net/browse/CPP-549) on our Jira board, it'll get planned and prioritised at some point. hopefully your workaround is suitable for now!
